# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libxml2-dev
      - r-cran-stringi
      - r-cran-dplyr
      - r-cran-ggplot2
after_success:
  - Rscript -e 'covr::codecov()'
